<h1><center>Entrega diagnóstico gitflow</center></h1>
<h2><center>IIC2154</center></h2>

Se exportan las librerias necesarias, se carga el dataframe (df) y se imprimen las primeras lineas (y sus tipos) para tener una mirada general del archivo.

In [1]:
import pandas as pd
import json
import re

In [2]:
df = pd.read_json("farmers-protest-tweets-2021-03-5.json", lines=True)

In [5]:
df.iloc[11]

url                https://twitter.com/anmoldhaliwal/status/13645...
date                                       2021-02-24 09:21:51+00:00
content            @mandeeppunia1 watch full video here https://t...
renderedContent    @mandeeppunia1 watch full video here youtu.be/...
id                                               1364505813834989568
user               {'username': 'anmoldhaliwal', 'displayname': '...
outlinks                              [https://youtu.be/-bUKumwq-J8]
tcooutlinks                                [https://t.co/wBPNdJdB0n]
replyCount                                                         0
retweetCount                                                       0
likeCount                                                          0
quoteCount                                                         0
conversationId                                   1364480983995584515
lang                                                              en
source             <a href="https://mobile.twitter.com" rel="nofo...
sourceUrl                                 https://mobile.twitter.com
sourceLabel                                          Twitter Web App
media              [{'thumbnailUrl': 'https://pbs.twimg.com/ext_t...
retweetedTweet                                                   NaN
quotedTweet                                                     None
mentionedUsers     [{'username': 'mandeeppunia1', 'displayname': ...
Name: 11, dtype: object

In [6]:
df.dtypes

url                             object
date               datetime64[ns, UTC]
content                         object
renderedContent                 object
id                               int64
user                            object
outlinks                        object
tcooutlinks                     object
replyCount                       int64
retweetCount                     int64
likeCount                        int64
quoteCount                       int64
conversationId                   int64
lang                            object
source                          object
sourceUrl                       object
sourceLabel                     object
media                           object
retweetedTweet                 float64
quotedTweet                     object
mentionedUsers                  object
dtype: object

1. Los top 10 tweets más retweeted
(Referencia: https://www.geeksforgeeks.org/python-pandas-dataframe-nlargest/)

In [7]:
def top_tweets(cantidad):
    top = df.nlargest(cantidad, 'retweetCount', keep='first')
    return top
top_tweets(10)

,url,date,content,renderedContent,id,user,outlinks,tcooutlinks,replyCount,retweetCount,...,quoteCount,conversationId,lang,source,sourceUrl,sourceLabel,media,retweetedTweet,quotedTweet,mentionedUsers
111329,https://twitter.com/RakeshTikaitBKU/status/136...,2021-02-12 10:10:56+00:00,मध्यप्रदेश में निजी व्यापारी 200 करोड़ का धान ...,मध्यप्रदेश में निजी व्यापारी 200 करोड़ का धान ...,1360169510079111173,"{'username': 'RakeshTikaitBKU', 'displayname':...",[],[],572,7723,...,309,1360169510079111173,hi,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None
7645,https://twitter.com/dhruv_rathee/status/136414...,2021-02-23 09:40:21+00:00,There's a #FarmersProtest happening in Germany...,There's a #FarmersProtest happening in Germany...,1364148079117615105,"{'username': 'dhruv_rathee', 'displayname': 'D...",[],[],666,6164,...,221,1364148079117615105,en,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,None
89780,https://twitter.com/rupikaur_/status/136088206...,2021-02-14 09:22:23+00:00,"disha ravi, a 21-year-old climate activist, ha...","disha ravi, a 21-year-old climate activist, ha...",1360882069161803779,"{'username': 'rupikaur_', 'displayname': 'rupi...",[https://scroll.in/latest/986851/greta-thunber...,[https://t.co/IYGsLpNjwZ],655,4673,...,388,1360882069161803779,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",https://mobile.twitter.com,Twitter Web App,None,NaN,None,"[{'username': 'GretaThunberg', 'displayname': ..."
88911,https://twitter.com/amaanbali/status/136090860...,2021-02-14 11:07:50+00:00,Disha Ravi broke down in court room and told j...,Disha Ravi broke down in court room and told j...,1360908603155050498,"{'username': 'amaanbali', 'displayname': 'Amaa...",[],[],282,3742,...,239,1360908603155050498,en,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None
111556,https://twitter.com/jedijasmin_/status/1360162...,2021-02-12 09:44:31+00:00,Farmers are so sweet. Y’all have to see this @...,Farmers are so sweet. Y’all have to see this @...,1360162861419425795,"{'username': 'jedijasmin_', 'displayname': 'Ja...",[],[],170,3332,...,175,1360162861419425795,en,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,"[{'username': 'AmandaCerny', 'displayname': 'A..."
64492,https://twitter.com/rupikaur_/status/136179092...,2021-02-16 21:33:51+00:00,india is targeting young women to silence diss...,india is targeting young women to silence diss...,1361790921902338048,"{'username': 'rupikaur_', 'displayname': 'rupi...",[],[],278,3230,...,230,1361790921902338048,en,"<a href=""https://mobile.twitter.com"" rel=""nofo...",https://mobile.twitter.com,Twitter Web App,None,NaN,None,None
108072,https://twitter.com/RaviSinghKA/status/1360260...,2021-02-12 16:11:35+00:00,Bollywood has betrayed Panjab &amp; the farmer...,Bollywood has betrayed Panjab &amp; the farmer...,1360260269646237699,"{'username': 'RaviSinghKA', 'displayname': 'ra...",[],[],294,3182,...,205,1360260269646237699,en,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None
60721,https://twitter.com/sherryontopp/status/136189...,2021-02-17 04:38:50+00:00,लहरों को ख़ामोश देख कर ये ना समझना कि समंदर मे...,लहरों को ख़ामोश देख कर ये ना समझना कि समंदर मे...,1361897874582249474,"{'username': 'sherryontopp', 'displayname': 'N...",[],[],277,3057,...,65,1361897874582249474,hi,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None
29510,https://twitter.com/sherryontopp/status/136309...,2021-02-20 11:38:08+00:00,"हाँ मैं जानता हूँ कि मैं शायर नहीं, और ज़ुल्म ...","हाँ मैं जानता हूँ कि मैं शायर नहीं, और ज़ुल्म ...",1363090557984141315,"{'username': 'sherryontopp', 'displayname': 'N...",[],[],312,3040,...,67,1363090557984141315,hi,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None
24160,https://twitter.com/sherryontopp/status/136337...,2021-02-21 06:33:27+00:00,"कलियुग है साहब , यहाँ झूठे को स्वीकार किया जा...","कलियुग है साहब , यहाँ झूठे को स्वीकार किया जा...",1363376268784267268,"{'username': 'sherryontopp', 'displayname': 'N...",[],[],212,2622,...,58,1363376268784267268,hi,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None

2. Los top 10 usuarios en función a la cantidad de tweets que emitieron.

In [20]:
def users_list(): #función para obtener todos los usernames
    users = []
    for user in df["user"]:
        u = user["username"]
        users.append(u)
    return users # lista con todos los nombres de usuario

In [38]:
def new_column(data): #función para agregar una nueva columna al dataframe
    df['username']= data
users = users_list()
new_column(users) #agregamos la nueva columna

In [83]:
def top_users(cantidad):
    df_groupby = df.groupby(['username']).count()
    top = df_groupby.nlargest(cantidad, 'content', keep='first')
    return top
top_users(10)

,url,date,content,renderedContent,id,user,outlinks,tcooutlinks,replyCount,retweetCount,...,quoteCount,conversationId,lang,source,sourceUrl,sourceLabel,media,retweetedTweet,quotedTweet,mentionedUsers
username,,,,,,,,,,,,,,,,,,,,,
jot__b,1019,1019,1019,1019,1019,1019,1019,1019,1019,1019,...,1019,1019,1019,1019,1019,1019,10,0,595,476
rebelpacifist,850,850,850,850,850,850,850,850,850,850,...,850,850,850,850,850,850,14,0,769,50
MaanDee08215437,830,830,830,830,830,830,830,830,830,830,...,830,830,830,830,830,830,51,0,750,90
Gurpreetd86,636,636,636,636,636,636,636,636,636,636,...,636,636,636,636,636,636,44,0,154,478
GurmVicky,597,597,597,597,597,597,597,597,597,597,...,597,597,597,597,597,597,22,0,394,17
shells_n_petals,576,576,576,576,576,576,576,576,576,576,...,576,576,576,576,576,576,5,0,545,51
preetysaini321,573,573,573,573,573,573,573,573,573,573,...,573,573,573,573,573,573,0,0,0,572
ish_kayy,515,515,515,515,515,515,515,515,515,515,...,515,515,515,515,515,515,18,0,310,241
KaurDosanjh1979,512,512,512,512,512,512,512,512,512,512,...,512,512,512,512,512,512,1,0,442,73
DigitalKisanBot,490,490,490,490,490,490,490,490,490,490,...,490,490,490,490,20,20,10,0,4,4

3. Los top 10 días donde hay más tweets.

In [87]:
def top_days(cantidad):
    df_groupby = df.groupby(['date']).count()
    top = df_groupby.nlargest(cantidad, 'id', keep='first')
    return top
top_days(10)

,url,content,renderedContent,id,user,outlinks,tcooutlinks,replyCount,retweetCount,likeCount,...,conversationId,lang,source,sourceUrl,sourceLabel,media,retweetedTweet,quotedTweet,mentionedUsers,username
date,,,,,,,,,,,,,,,,,,,,,
2021-02-20 12:57:17+00:00,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,6,0,0,1,7
2021-02-17 04:46:58+00:00,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,0,0,1,0,6
2021-02-15 02:43:08+00:00,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,1,0,4,0,5
2021-02-23 05:05:55+00:00,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,2,0,3,0,5
2021-02-12 03:04:44+00:00,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,0,0,0,1,4
2021-02-12 04:52:08+00:00,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,0,0,4,0,4
2021-02-12 17:11:11+00:00,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,0,0,1,1,4
2021-02-13 05:28:34+00:00,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,0,0,0,1,4
2021-02-13 05:30:13+00:00,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,1,0,0,1,4
2021-02-13 05:32:56+00:00,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,0,0,1,1,4

4. Top 10 hashtags más usados.